### PR TITLE
ci: Orb tools 11 migration

### PR DESCRIPTION
**Pull request by Jaryt**

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gradle?version=dev:66043c96858226824295b3fee0da67853bd9cbce

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gradle?version=dev:66043c96858226824295b3fee0da67853bd9cbce

**Review by KyleTryon — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gradle?version=dev:614c0e5c30fe2d87b34b91beff183310e117cffa

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gradle?version=dev:614c0e5c30fe2d87b34b91beff183310e117cffa

**Pull request merged**
